# # Name : Ahmar Ayaz

# # Roll No. : PIAIC115032

In [2]:
#Q. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.19.4


In [3]:
#Q. Create a 1D array of numbers from 0 to 9
array=np.arange(10)
print (array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Q. Create a 3×3 numpy array of all True’s
array=np.ones((3,3),dtype=bool) #np.ones makes an array filled with ones only, (3,3) specifies block size, dtype specifies data type
print (array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr)
arr[arr%2==1] # make an array from values where %2 =1 (odd numbers)

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [6]:
#Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1 # =-1 tells to replace the odd numbers with -1

In [7]:
#Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reparr=np.where(arr%2==1,-1,arr)
print(arr)
print(reparr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#Q. Convert a 1D array to a 2D array with 2 rows
array=np.arange(10)
print(array.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#Q. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
print("array a")
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print("array b")
print(b)
print("a and b stacked vertically")
print(np.concatenate([a, b], axis=0))

array a
[[0 1 2 3 4]
 [5 6 7 8 9]]
array b
[[1 1 1 1 1]
 [1 1 1 1 1]]
a and b stacked vertically
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
#Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
print("array b")
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print("array b")
print(b)
print("array a and b stacked horizontally")
print(np.concatenate([a, b], axis=1))

array b
[[0 1 2 3 4]
 [5 6 7 8 9]]
array b
[[1 1 1 1 1]
 [1 1 1 1 1]]
array a and b stacked horizontally
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [11]:
#Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
print(a)
print(np.r_[np.repeat(a, 3), np.tile(a, 3)]) #using the function to repeat the array

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [12]:
#Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b)) # .intersect1d gets the common items

[2 4]


In [13]:
#Q. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b)) #.setdiff1d gets the different items 

[1 2 3 4]


In [14]:
#Q. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b)) # prints where a==b

(array([1, 3, 5, 7]),)


In [15]:
#Q. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [16]:
#Q. Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [17]:
#Q. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
print("after swapping columns 1 and 2")
print(arr[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
after swapping columns 1 and 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [29]:
#Q. Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
print(arr)
#solution
arr[[1,0,2], :]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [28]:
#Q. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [31]:
#Q. Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [34]:
#Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
rand_arr = np.random.uniform(5,10, size=(5,3))# np.random to use the random function. 5,10 tell us range of values 
print(rand_arr)# size 5,3 tells size of the array to make

[[8.31411181 7.73181817 6.59096717]
 [5.50339937 6.86703562 8.31240744]
 [5.35250022 6.83792513 6.56461284]
 [5.72583021 5.01738796 6.45301192]
 [5.73982147 8.34745601 7.18559825]]


In [40]:
#Q. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
print(rand_arr)
np.set_printoptions(precision=3)#tells us to set the precision to 3 decimal places
rand_arr[:4]
np.set_printoptions(suppress=False) #reset print options

[[0.175 0.373 0.006]
 [0.252 0.796 0.015]
 [0.599 0.604 0.105]
 [0.382 0.036 0.89 ]
 [0.981 0.06  0.891]]


In [44]:
#Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr
np.set_printoptions(suppress=True,precision=7)
print(rand_arr)


[[0.0005434 0.0002784 0.0004245]
 [0.0008448 0.0000047 0.0001216]
 [0.0006707 0.0008259 0.0001367]]


In [45]:
#Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
np.set_printoptions(threshold=6)#limit the printoptions threshold to 6
a = np.arange(15)
a# the limit will cause us to print only 6 elements

array([ 0,  1,  2, ..., 12, 13, 14])

In [52]:
#Q. Print the full numpy array a without truncating.
np.set_printoptions(threshold=6)
a = np.arange(15)
a
np.set_printoptions(threshold=np.sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
#Q. Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:5] # check to see data is intant

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [55]:
#Q. Extract the text column species from the 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


<ipython-input-55-9e55ad05ddbf>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [56]:
#Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

<ipython-input-56-0b787b0726f7>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [58]:
#Q. Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean, median, standard_deviation = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, median, standard_deviation)

5.843333333333334 5.8 0.8253012917851409


In [59]:
#Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)

[0.2222222 0.1666667 0.1111111 0.0833333 0.1944444 0.3055556 0.0833333
 0.1944444 0.0277778 0.1666667 0.3055556 0.1388889 0.1388889 0.
 0.4166667 0.3888889 0.3055556 0.2222222 0.3888889 0.2222222 0.3055556
 0.2222222 0.0833333 0.2222222 0.1388889 0.1944444 0.1944444 0.25
 0.25      0.1111111 0.1388889 0.3055556 0.25      0.3333333 0.1666667
 0.1944444 0.3333333 0.1666667 0.0277778 0.2222222 0.1944444 0.0555556
 0.0277778 0.1944444 0.2222222 0.1388889 0.2222222 0.0833333 0.2777778
 0.1944444 0.75      0.5833333 0.7222222 0.3333333 0.6111111 0.3888889
 0.5555556 0.1666667 0.6388889 0.25      0.1944444 0.4444444 0.4722222
 0.5       0.3611111 0.6666667 0.3611111 0.4166667 0.5277778 0.3611111
 0.4444444 0.5       0.5555556 0.5       0.5833333 0.6388889 0.6944444
 0.6666667 0.4722222 0.3888889 0.3333333 0.3333333 0.4166667 0.4722222
 0.3055556 0.4722222 0.6666667 0.5555556 0.3611111 0.3333333 0.3333333
 0.5       0.4166667 0.1944444 0.3611111 0.3888889 0.3888889 0.5277778
 0.2222222 0.38888

In [60]:
#Q. Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = np.array([float(row[0]) for row in iris])
def softmax(x):
    """Compute softmax values for each sets of scores in x."""#found on https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
print(softmax(sepallength))

[0.0022196 0.0018172 0.0014878 0.0013462 0.0020084 0.0029961 0.0013462
 0.0020084 0.0011022 0.0018172 0.0029961 0.0016443 0.0016443 0.0009973
 0.0044697 0.0040443 0.0029961 0.0022196 0.0040443 0.0022196 0.0029961
 0.0022196 0.0013462 0.0022196 0.0016443 0.0020084 0.0020084 0.002453
 0.002453  0.0014878 0.0016443 0.0029961 0.002453  0.0033112 0.0018172
 0.0020084 0.0033112 0.0018172 0.0011022 0.0022196 0.0020084 0.0012181
 0.0011022 0.0020084 0.0022196 0.0016443 0.0022196 0.0013462 0.002711
 0.0020084 0.0148399 0.0081443 0.0134277 0.0033112 0.0090009 0.0040443
 0.0073693 0.0018172 0.0099475 0.002453  0.0020084 0.0049398 0.0054593
 0.0060335 0.0036595 0.0109937 0.0036595 0.0044697 0.006668  0.0036595
 0.0049398 0.0060335 0.0073693 0.0060335 0.0081443 0.0099475 0.0121499
 0.0109937 0.0054593 0.0040443 0.0033112 0.0033112 0.0044697 0.0054593
 0.0029961 0.0054593 0.0109937 0.0073693 0.0036595 0.0033112 0.0033112
 0.0060335 0.0044697 0.0020084 0.0036595 0.0040443 0.0040443 0.006668
 0.002219

In [61]:
#Q. Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [66]:
#Q. Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
i, j = np.where(iris_2d)
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [67]:
#Q. Find the number and position of missing values in iris_2d's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print("Number of missing values: ", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: ", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values:  5
Position of missing values:  (array([13, 17, 47, 53, 91]),)


In [68]:
#Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)# set the condition
iris_2d[condition]#print the array after follwoing our condition

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [69]:
#Q. Select the rows of iris_2d that does not have any nan value.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5] # print out rows which dont have nan values

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [70]:
#Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]#using the corrcoef function


0.8717541573048718

In [71]:
#Q. Find out if iris_2d has any missing values.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()#using the isnan function 

False

In [76]:
#Q. Replace all ccurrences of nan with 0 in numpy array
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan#replace places with nan with random integers
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [77]:
#Q. Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)#using the np.unique function we can check for unique species by the true condition

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50]))

In [78]:
""""Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

    Less than 3 --> 'small'
    3-5 --> 'medium'
    '>=5 --> 'large'"""
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10]) # bin the petal length
map_petal = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}#map petal to category
petal_length_cat = [map_petal[x] for x in petal_length_bin]
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [81]:
#Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris_2d[:, 0].astype('float')#change the datatype
petallength = iris_2d[:, 2].astype('float')#change the datatype
volume = (np.pi * petallength * (sepallength**2))/3#calculate volume
volume = volume[:, np.newaxis]#change to new dimension
result = np.hstack([iris_2d, volume])
print(result[:6])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 36.65191429188092]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 51.911677007917746]]


In [82]:
#Q. What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')#get the required columns and change the datatype to float
np.unique(np.sort(petal_len_setosa))[-2] # by usin -2 we specify that we get the 2nd longest length

1.7

In [83]:
#Q. Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[iris[:,0].argsort()][:6])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']]


In [84]:
#Q. Find the most frequent value of petal length (3rd column) in iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
vals, counts = np.unique(iris[:, 2], return_counts=True)#get unique values
print(vals[np.argmax(counts)])#return argmax of the counts of values we got

b'1.5'


In [85]:
#Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

In [86]:
#Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.6268421 14.6400999 21.8013619 30.        10.        10.
 30.        30.        10.        29.1795731 30.        11.250904
 10.0810828 10.        11.7651771 30.        30.        10.
 30.        14.4296136]


In [87]:
#Q. Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a.argsort()][-5:]#using argsort and -5 we get the top 5 max values

array([40.9950127, 41.466785 , 42.3940305, 44.6747758, 48.9525655])

In [92]:
#Q. Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print(array_of_arrays)
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


<ipython-input-92-51a398644a6d>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  array_of_arrays = np.array([arr1, arr2, arr3])


In [93]:
#Q. Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
print(a.argsort().argsort())
print('Array: ', a)

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [94]:
#Q. Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print(np.amax(a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
